version: "3"

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumen_php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Composer Service
  composer:
    image: composer:latest
    container_name: composer
    tty: true
    volumes:
      - ./:/app
    networks:
      - app-network
    command: composer install

  # #Nginx Service
  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
